name: Live Player Count

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Lua & Luarocks
        run: |
          sudo apt update
          sudo apt install -y lua5.3 luarocks
          luarocks install luasocket
          luarocks install dkjson

      - name: Run live_count.lua
        run: |
          nohup lua live_count.lua &
