name: Growtopia Live Player Count

on:
  workflow_dispatch:  # Hanya berjalan saat dipicu manual

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Lua
        run: |
          sudo apt update
          sudo apt install lua5.3 -y  # Install Lua 5.3

      - name: Run Growtopia Live Count Script (6 Jam)
        run: timeout 6h lua count.lua  # Menjalankan script selama 6 jam
